import json
import os
import sys
import tempfile
from pathlib import Path

from yt_dlp import YoutubeDL


def cookie_header_to_file(cookie_str, domain=".douyin.com"):
    """Convert a Cookie header string to a Netscape cookie file for yt-dlp."""
    if not cookie_str or not cookie_str.strip():
        return None
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Bluebird for yt-dlp",
        "",
    ]
    for part in cookie_str.split(";"):
        part = part.strip()
        if "=" not in part:
            continue
        name, value = part.split("=", 1)
        name = name.strip()
        value = value.strip()
        if not name:
            continue
        # domain, flag, path, secure, expiry, name, value
        lines.append(f"{domain}\tTRUE\t/\tFALSE\t0\t{name}\t{value}")

    if len(lines) <= 3:
        return None

    fd, path = tempfile.mkstemp(suffix=".txt", prefix="dy_cookie_")
    with os.fdopen(fd, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def fetch_fresh_cookies(user_agent):
    """Fetch ttwid session cookie from Bytedance's API, then visit douyin.com for remaining cookies."""
    import http.cookiejar
    import urllib.request

    jar = http.cookiejar.MozillaCookieJar()
    opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(jar))

    # Step 1: Get ttwid from Bytedance's register API
    ttwid_payload = json.dumps({
        "region": "cn",
        "aid": 1128,
        "needFid": False,
        "service": "www.douyin.com",
        "migrate_info": {"ticket": "", "source": "node"},
        "cbUrlProtocol": "https",
        "union": True,
    }).encode()
    try:
        req = urllib.request.Request(
            "https://ttwid.bytedance.com/ttwid/union/register/",
            data=ttwid_payload,
            headers={
                "User-Agent": user_agent,
                "Content-Type": "application/json",
            },
        )
        opener.open(req, timeout=10)
    except Exception:
        pass

    # Step 2: Visit douyin.com to get additional cookies
    try:
        req2 = urllib.request.Request(
            "https://www.douyin.com/",
            headers={"User-Agent": user_agent},
        )
        opener.open(req2, timeout=10)
    except Exception:
        pass

    if not jar:
        return None

    # Duplicate cookies to .douyin.com — yt-dlp looks up cookies by the video URL domain
    import http.cookiejar as hc
    extras = []
    for c in jar:
        if c.domain and "douyin" not in c.domain:
            dup = hc.Cookie(
                version=c.version, name=c.name, value=c.value,
                port=c.port, port_specified=c.port_specified,
                domain=".douyin.com", domain_specified=True, domain_initial_dot=True,
                path=c.path, path_specified=c.path_specified,
                secure=c.secure, expires=c.expires, discard=c.discard,
                comment=c.comment, comment_url=c.comment_url, rest=c._rest,
            )
            extras.append(dup)
    for dup in extras:
        jar.set_cookie(dup)

    fd, path = tempfile.mkstemp(suffix=".txt", prefix="dy_cookie_")
    os.close(fd)
    jar.save(path, ignore_discard=True, ignore_expires=True)
    return path


def read_payload():
    raw = sys.stdin.read()
    if not raw:
        raise ValueError("missing input payload")
    payload = json.loads(raw)
    return {
        "url": payload.get("url", "").strip(),
        "userAgent": payload.get("userAgent", "").strip(),
        "cookie": payload.get("cookie", "").strip(),
        "download": bool(payload.get("download", False)),
    }


def normalize_publish_at(timestamp):
    if not timestamp:
        return ""
    try:
        return int(timestamp)
    except Exception:
        return ""


def build_meta(info, fallback_url):
    return {
        "videoId": str(info.get("id") or "").strip(),
        "title": str(info.get("title") or "抖音视频").strip(),
        "author": str(
            info.get("uploader")
            or info.get("uploader_id")
            or info.get("channel")
            or "抖音作者"
        ).strip(),
        "duration": int(info.get("duration") or 0),
        "timestamp": normalize_publish_at(info.get("timestamp")),
        "webpageUrl": str(info.get("webpage_url") or fallback_url).strip(),
    }


def extract(payload):
    work_dir = Path(tempfile.mkdtemp(prefix="dy_dl_"))
    output_template = str(work_dir / "audio.%(ext)s")
    cookie_file = None

    headers = {
        "Referer": "https://www.douyin.com/",
        "User-Agent": payload["userAgent"],
    }

    # Douyin extractor requires cookies via cookie jar, not HTTP headers
    cookie_file = cookie_header_to_file(payload["cookie"])
    if not cookie_file:
        # No explicit cookie → fetch fresh session cookies automatically
        cookie_file = fetch_fresh_cookies(payload["userAgent"])

    ydl_opts = {
        "quiet": True,
        "noprogress": True,
        "noplaylist": True,
        "http_headers": headers,
        "outtmpl": output_template,
        "skip_download": not payload["download"],
    }

    if cookie_file:
        ydl_opts["cookiefile"] = cookie_file

    if payload["download"]:
        ydl_opts["format"] = "ba/b"
        ydl_opts["postprocessors"] = [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
                "preferredquality": "192",
            }
        ]
    else:
        # For metadata-only, any format is fine
        ydl_opts["format"] = "bv*+ba/b"

    try:
        with YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(payload["url"], download=payload["download"])
            meta = build_meta(info, payload["url"])
            if not payload["download"]:
                return {
                    "meta": meta,
                    "workDir": str(work_dir),
                }
    except Exception as e:
        error_msg = str(e)
        if "Unsupported URL" in error_msg or "generic" in error_msg.lower():
            raise RuntimeError(
                "抖音链接不被支持，请使用 douyin.com/video/xxx 格式的链接，"
                "或尝试更新 yt-dlp：pip install -U yt-dlp"
            )
        elif "forbidden" in error_msg.lower() or "403" in error_msg:
            raise RuntimeError("访问被拒绝：可能需要 Cookie，请在设置页配置抖音 Cookie")
        elif "timeout" in error_msg.lower():
            raise RuntimeError("下载超时：网络连接不稳定，请稍后重试")
        else:
            raise RuntimeError(f"抖音下载失败：{error_msg}")

    audio_path = work_dir / "audio.mp3"
    if not audio_path.exists():
        for item in work_dir.iterdir():
            if item.suffix.lower() in (".mp3", ".m4a", ".opus", ".webm", ".ogg"):
                audio_path = item
                break

    if not audio_path.exists():
        raise RuntimeError("音频下载成功但找不到文件")

    return {
        "meta": meta,
        "audioPath": str(audio_path),
        "workDir": str(work_dir),
    }


def main():
    payload = read_payload()
    if not payload["url"]:
        raise ValueError("url is required")
    if not payload["userAgent"]:
        payload["userAgent"] = (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
        )

    result = extract(payload)
    # Clean up any temporary cookie file
    for f in Path(tempfile.gettempdir()).glob("dy_cookie_*.txt"):
        try:
            f.unlink()
        except OSError:
            pass
    print(json.dumps(result))


if __name__ == "__main__":
    try:
        main()
    except Exception as err:
        print(str(err), file=sys.stderr)
        sys.exit(1)
